/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/calaveras.glb --transform --simplify
Author: Keith Ito (https://sketchfab.com/keithito)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/calaveras-f63aaf76233540d3801647c8e47fc17e
Title: Calaveras
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Calaveras(props) {
	const { nodes, materials } = useGLTF("/calaveras-transformed.glb");
	return (
		<group {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]}>
				<mesh
					geometry={nodes.Object_2.geometry}
					material={materials.main}
				/>
				<mesh
					geometry={nodes.Object_3.geometry}
					material={materials.main}
				/>
				<mesh
					geometry={nodes.Object_4.geometry}
					material={materials.main}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/calaveras-transformed.glb");
