/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/mexican_graffiti_wall_photogrammetry_scan.glb --transform --simplify
Author: photogrammexico (https://sketchfab.com/photogrammexico)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mexican-graffiti-wall-photogrammetry-scan-e62fd46269de49f4b76031eee042daea
Title: Mexican graffiti wall photogrammetry scan
*/

import React, { useLayoutEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Graffiti(props) {
	const { tl, ...otherProps } = props;
	const { nodes, materials } = useGLTF(
		"/mexican_graffiti_wall_photogrammetry_scan-transformed.glb",
	);

	const ref = useRef();

	useLayoutEffect(() => {
		if (tl) {
			tl.to(
				ref.current.position,
				{
					z: 0,
					duration: 0.75,
					ease: "power3.out",
				},
				2,
			);

			tl.to(ref.current.rotation, { y: Math.PI / 2, duration: 2 }, 3);
		}
	}, [tl]);
	return (
		<group ref={ref} {...otherProps} dispose={null}>
			<group
				position={[-2.98, 2.52, -5.28]}
				rotation={[-1.96, 0.16, -0.56]}
			>
				<mesh
					geometry={nodes.Object_2.geometry}
					material={materials["mexican_grafiti_wall.1001"]}
				/>
				<mesh
					geometry={nodes.Object_3.geometry}
					material={materials["mexican_grafiti_wall.1001"]}
				/>
				<mesh
					geometry={nodes.Object_4.geometry}
					material={materials["mexican_grafiti_wall.1001"]}
				/>
				<mesh
					geometry={nodes.Object_5.geometry}
					material={materials["mexican_grafiti_wall.1001"]}
				/>
				<mesh
					geometry={nodes.Object_6.geometry}
					material={materials["mexican_grafiti_wall.1001"]}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/mexican_graffiti_wall_photogrammetry_scan-transformed.glb");
