/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/day_of_the_dead_environment.glb --transform --simplify
Author: Jeff de Guzman (https://sketchfab.com/reyknow)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/day-of-the-dead-environment-0ca274a555ac4411b80d60b0e2f188a3
Title: Day of the Dead Environment
*/

import React, { useLayoutEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

export function Map(props) {
	const { tl, ...otherProps } = props;
	const { nodes, materials } = useGLTF(
		"/day_of_the_dead_environment-transformed.glb",
	);

	const ref = useRef();

	useLayoutEffect(() => {
		Object.values(materials).forEach((material) => {
			material.envMapIntensity = 0.4;
			material.opacity = 0;
			material.transparent = true;

			if (tl) {
				tl.to(
					material,
					{
						opacity: 1,
						duration: 1,
						ease: "power0.inOut",
					},
					4,
				);
			}
		});
	}, [tl]);
	return (
		<group {...otherProps} ref={ref} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]}>
				<mesh
					geometry={nodes.Object_2.geometry}
					material={materials.lambert2SG}
				/>
				<mesh
					geometry={nodes.Object_3.geometry}
					material={materials.lambert3SG}
				/>
				<mesh
					geometry={nodes.Object_4.geometry}
					material={materials.lambert3SG}
				/>
				<mesh
					geometry={nodes.Object_5.geometry}
					material={materials.lambert3SG}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/day_of_the_dead_environment-transformed.glb");
