/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/skull_day_of_the_dead.glb --transform --simplify
Author: jkazulyblanco (https://sketchfab.com/jkazulyblanco)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/skull-day-of-the-dead-f3f5325fb6444bd9bd550acac1e7edef
Title: Skull day of the dead
*/

import React, { useLayoutEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Skull(props) {
	const { tl, ...otherProps } = props;
	const { nodes, materials } = useGLTF(
		"/skull_day_of_the_dead-transformed.glb",
	);

	const skull = useRef();
	const jaw = useRef();
	const teeth = useRef();

	useLayoutEffect(() => {
		if (tl) {
			tl.to(
				jaw.current.rotation,
				{
					x: Math.PI * 0.1,
					duration: 1,
					ease: "power3.out",
				},
				1.15,
			);
			tl.to(
				jaw.current.position,
				{
					y: -0.5,
					duration: 1.75,
					ease: "power3.out",
				},
				1.5,
			);

			tl.to(
				teeth.current.position,
				{
					y: -0.3,
					duration: 1.75,
					ease: "power3.out",
				},
				1.5,
			);
		}
	}, [tl]);

	return (
		<group {...otherProps} ref={skull} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]}>
				<group rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						geometry={nodes.defaultMaterial.geometry}
						material={materials["1001"]}
					/>
					<mesh
						ref={jaw}
						geometry={nodes.defaultMaterial_1.geometry}
						material={materials["1002"]}
					/>
					<mesh
						ref={teeth}
						geometry={nodes.defaultMaterial_2.geometry}
						material={materials["1003"]}
					/>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/skull_day_of_the_dead-transformed.glb");
